import datetime
import queue
from abc import ABC, abstractmethod

from core.events import FillEvent, OrderEvent
from data.base import BaseDataHandler


class ExecutionHandler(ABC):
    """the executionhandler abstract class handles the interaction.
    between a set of order objects generated by a portfolio and.
    the ultimate set of fill objects that actually occur in the.
    market."""

    @abstractmethod
    def execute_order(self, event: OrderEvent) -> None:
        pass


class SimulatedBroker(ExecutionHandler):
    """the simulated execution handler simply converts all order.
    objects into their equivalent fill objects automatically.
    without latency slippage or fill ratio issues.
    this allows a straightforward first go test of any strategy.
    before implementation with a more sophisticated execution handler."""

    def __init__(self, events: queue.Queue, data_handler: BaseDataHandler, config=None) -> None:
        self.events = events
        self.data_handler = data_handler
        self.config = config

    def execute_order(self, event: OrderEvent) -> None:
        """simply converts order objects into fill objects naively.
        i.e. without any latency slippage or fill ratio problems."""
        if event.type == "ORDER":
            price_col = (
                getattr(self.config.broker, "execution_price", "Close")
                if self.config and hasattr(self.config, "broker")
                else "Close"
            )
            try:
                fill_cost = self.data_handler.get_latest_bar_value(event.symbol, price_col)
            except (KeyError, ValueError):
                fill_cost = self.data_handler.get_latest_bar_value(event.symbol, "Close")

            brokerage = 0.0
            stt = 0.0
            gst = 0.0
            exc = 0.0
            stamp = 0.0
            sebi = 0.0
            total_charges = 0.0

            if (
                self.config
                and getattr(self.config, "broker", None)
                and getattr(self.config.broker, "charges", {}).get("enabled", False)
            ):
                from markets.india.brokers import get_broker_charges

                broker_engine = get_broker_charges(self.config.broker.name)
                charges = broker_engine.calculate_charges(
                    product=self.config.broker.product,
                    price=fill_cost,
                    qty=event.quantity,
                    direction=event.direction,
                )
                brokerage = charges["brokerage"]
                stt = charges["stt"]
                gst = charges["gst"]
                exc = charges["exchange_txn"]
                stamp = charges["stamp_duty"]
                sebi = charges["sebi"]
                total_charges = charges["total"]

            bar_dt = self.data_handler.get_latest_bar_datetime(event.symbol)
            if bar_dt is None:
                bar_dt = datetime.datetime.now(datetime.timezone.utc)

            fill_event = FillEvent(
                timeindex=bar_dt,
                symbol=event.symbol,
                exchange="NSE",
                quantity=event.quantity,
                direction=event.direction,
                fill_cost=fill_cost,
                commission=total_charges if total_charges > 0 else None,
            )

            # use object. setattr because fillevent is frozen.
            object.__setattr__(fill_event, "brokerage", brokerage)
            object.__setattr__(fill_event, "stt", stt)
            object.__setattr__(fill_event, "gst", gst)
            object.__setattr__(fill_event, "exchange_charges", exc)
            object.__setattr__(fill_event, "stamp_duty", stamp)
            object.__setattr__(fill_event, "sebi_fees", sebi)
            if total_charges > 0:
                object.__setattr__(fill_event, "commission", total_charges)

            self.events.put(fill_event)
